typography_spectrum: 0.3588260046672076
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.05229488108307123
  lightness: 0.6294095027260482
  saturation: 0.9408418154343963
  rhythmicContrast: 0.17540391837246716
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8269734585192055
analytics:
  google: null
  facebook: null
  twitter: null
name: Hello!
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: My Twitter
    url: 'https://twitter.com/vandenbogerd'
    type: external
favicon: null
title: Frank Van den Bogerd
description: Zaakvoerder @multimedium
purpose: []
